version: '3.3'

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
       - ./data:/var/lib/postgresql/data

  tgbot:
    build: .
    depends_on:
      - mongo-db
