version: '3.3'

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
       - ./data:/data/db

  tgbot:
    build: .
    depends_on:
      - mongo-db
